# Copyright (c) 2019 Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################
# Global configuration defaults.
#################################################################
global:
  # Change to an unused port prefix range to prevent port conflicts
  # with other instances running within the same k8s cluster
  nodePortPrefix: 302

  # image repositories
  #repository: nexus3.onap.org:10001
  repository: image-registry.openshift-image-registry.svc:5000
  # readiness check
  #readinessImage: onap/oom/readiness:3.0.1
  readinessImage: onap/readiness:3.0.1


  # image pull policy
  pullPolicy: Always

  persistence:
    mountPath: /dockerdata-nfs

#################################################################
# Application configuration defaults.
#################################################################
# application image
#repository: nexus3.onap.org:10001
repository: image-registry.openshift-image-registry.svc:5000
#image: onap/ccsdk-sdclistener:1.0.3
image: onap/ccsdk-sdclistener:latest
name: sdc-listener
pullPolicy: Always

# flag to enable debugging - application support required
debugEnabled: false

# application configuration
config:
  appConfigDir: /opt/app/onap/config

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 10
  periodSeconds: 300
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 10
  periodSeconds: 300

service:
  type: ClusterIP
  http:
    portName: cds-sdc-listener-http
    internalPort: 8080
    externalPort: 8080

persistence:
  enabled: true

ingress:
  enabled: false

logback:
  rootLogLevel: INFO
  logger:
    springframework: INFO
    springframeworkWeb: INFO
    springframeworkSecurityWebauthentication: INFO
    hibernate: INFO
    onapCcsdkCds: INFO

flavor: small

resources:
  small:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 512Mi
  large:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 200m
      memory: 512Mi
  unlimited: {}
